
spring:
  profiles:
    active: local
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
---
spring:
  datasource:
  url: jdbc:h2:tcp://localhost/~/auction
  username: sa
  password:
  driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      show_sql: true
#      format_sql : true
       hibernate:
         format_sql: true
  config:
    activate:
      on-profile:
---
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  config:
    activate:
      on-profile: dev