
spring:
  profiles:
    active: local
---
spring:
  datasource:
  url: jdbc:h2:tcp://localhost/~/auction
  username: sa
  password:
  driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql : true
  config:
    activate:
      on-profile:
---
server:
  port: 8000
logging:
  level:
    org.hibernate.SQL: debug
spring:
  config:
    activate:
      on-profile: